#!/bin/bash
# The OpenRC service and the launcher every CTech Go service shares — Alpine
# equivalent of assets/ec2/setup-app-service.sh. Same start.sh env-layering
# contract (release.env, then load-ssm-env.sh, then service-env.sh).
#
# Usage: setup-app-service.sh <description> <binary-name> [alt-port]
#   setup-app-service.sh "CTech Wallet API" app
#   setup-app-service.sh "CTech Wallet API" app 8081
set -euo pipefail

DESCRIPTION="${1:?setup-app-service.sh: unit description required}"
BINARY="${2:?setup-app-service.sh: binary name required}"
ALT_PORT="${3:-}"

mkdir -p /opt/app

cat > /opt/app/start.sh << 'START'
#!/bin/bash
# Generated by setup-app-service.sh — do not edit. Per-service configuration
# belongs in /opt/app/service-env.sh.
if [ -f /etc/app-static.env ]; then set -a; . /etc/app-static.env; set +a; fi
if [ -f /opt/app/current/release.env ]; then set -a; . /opt/app/current/release.env; set +a; fi
if [ -f /opt/app/load-ssm-env.sh ]; then . /opt/app/load-ssm-env.sh; fi
if [ -f /opt/app/service-env.sh ]; then . /opt/app/service-env.sh; fi
if [ -n "${PORT_OVERRIDE:-}" ]; then PORT="$PORT_OVERRIDE"; export PORT; fi
exec /opt/app/current/__BINARY__
START
sed -i "s|__BINARY__|${BINARY}|g" /opt/app/start.sh
chmod 0755 /opt/app/start.sh

cat > /etc/init.d/app << 'SVC'
#!/sbin/openrc-run
description="__DESCRIPTION__"
command="/opt/app/start.sh"
command_user="webapp:webapp"
command_background="yes"
pidfile="/run/app.pid"
supervisor="supervise-daemon"
respawn_delay=30
respawn_max=0
output_log="/var/log/app/app.log"
error_log="/var/log/app/app.log"

depend() {
	need net
}
SVC
sed -i "s|__DESCRIPTION__|${DESCRIPTION}|g" /etc/init.d/app
chmod 0755 /etc/init.d/app
rc-update add app default

if [ -n "$ALT_PORT" ]; then
  cat > /etc/init.d/app2 << 'SVC2'
#!/sbin/openrc-run
description="__DESCRIPTION__ (alt)"
command="/opt/app/start.sh"
command_user="webapp:webapp"
command_background="yes"
pidfile="/run/app2.pid"
supervisor="supervise-daemon"
respawn_delay=30
respawn_max=0
export PORT_OVERRIDE="__ALT_PORT__"
output_log="/var/log/app/app2.log"
error_log="/var/log/app/app2.log"

depend() {
	need net
}
SVC2
  sed -i \
    -e "s|__DESCRIPTION__|${DESCRIPTION}|g" \
    -e "s|__ALT_PORT__|${ALT_PORT}|g" \
    /etc/init.d/app2
  chmod 0755 /etc/init.d/app2
  rc-update add app2 default
  echo "$ALT_PORT" > /opt/app/alt-port
fi
