#!/bin/bash
# Generates /opt/app/load-ssm-env.sh from VAR=/ssm/path pairs. Alpine
# equivalent of assets/ec2/setup-ssm-env.sh: reads via ctech-ec2-agent
# ssm-get instead of the AWS CLI, same read-at-start contract.
#
# Usage: setup-ssm-env.sh VAR=/ssm/path [VAR=/ssm/path ...]
set -euo pipefail

OUT=/opt/app/load-ssm-env.sh

[ "$#" -gt 0 ] || { echo "setup-ssm-env.sh: at least one VAR=/ssm/path pair required" >&2; exit 1; }

for pair in "$@"; do
  case "$pair" in
    *=/*) ;;
    *) echo "setup-ssm-env.sh: expected VAR=/ssm/path, got '$pair'" >&2; exit 1 ;;
  esac
done

mkdir -p /opt/app
{
  echo '# Generated by setup-ssm-env.sh — do not edit.'
  echo '_ctech_ssm(){ ctech-ec2-agent ssm-get -name "$1" 2>/dev/null || echo ""; }'
  for pair in "$@"; do
    name="${pair%%=*}"
    ssm_path="${pair#*=}"
    printf '%s=$(_ctech_ssm %q)\n' "$name" "$ssm_path"
  done
} > "$OUT"
chmod 0644 "$OUT"
