#!/bin/bash
# Alpine/OpenRC equivalent of assets/ec2/setup-realip.sh. Same trust-chain
# reasoning (walk X-Forwarded-For right-to-left, discard only HAProxy then
# CloudFront's origin-facing ranges) — only the AWS call and the scheduling
# mechanism differ: ctech-ec2-agent instead of the AWS CLI, /etc/periodic
# instead of a systemd timer (OpenRC has no timer unit, so the daily script
# jitters its own start with `sleep $((RANDOM % 3600))`).
#
# Usage: setup-realip.sh <vpc-ipv4-cidr>
set -euo pipefail

VPC_CIDR="${1:?setup-realip.sh: VPC IPv4 CIDR required}"

mkdir -p /opt/app /etc/nginx/conf.d /etc/periodic/daily

cat > /opt/app/update-realip.sh << 'REALIP'
#!/bin/bash
set -euo pipefail
CONF=/etc/nginx/conf.d/realip.conf
TMP=$(mktemp)
export AWS_USE_DUALSTACK_ENDPOINT=true
PREFIXES=$(ctech-ec2-agent prefix-list -name com.amazonaws.global.cloudfront.origin-facing -region us-east-1)
if [ "$(echo "$PREFIXES" | grep -c .)" -lt 10 ]; then
  echo "Refusing to write realip.conf: only $(echo "$PREFIXES" | grep -c .) CloudFront prefixes returned" >&2
  exit 1
fi
{
  echo "# Generated by /opt/app/update-realip.sh — do not edit."
  echo "set_real_ip_from __VPC_CIDR__;"
  echo "$PREFIXES" | sed -e 's|^|set_real_ip_from |' -e 's|$|;|'
  echo "real_ip_header X-Forwarded-For;"
  echo "real_ip_recursive on;"
} > "$TMP"
install -m 644 "$TMP" "$CONF"
rm -f "$TMP"
# nginx -t here validates the WHOLE current nginx.conf, not just this file.
# Called from userData, this runs before setup-nginx.sh has written the real
# nginx.conf — at that point nginx -t is testing Alpine's stock config, which
# (unlike AL2023's RPM) does not include conf.d/*.conf by default, so it
# always fails on first boot. Keep the file regardless: setup-nginx.sh's own
# nginx -t (run after, against the real config) is what actually validates
# it, and only reload here when nginx is already up with a config that
# accepts it — never delete it back out.
if nginx -t 2>/dev/null && rc-service nginx status >/dev/null 2>&1; then
  rc-service nginx reload
fi
REALIP
sed -i "s|__VPC_CIDR__|${VPC_CIDR}|g" /opt/app/update-realip.sh
chmod +x /opt/app/update-realip.sh

cat > /etc/periodic/daily/ctech-realip << 'PERIODIC'
#!/bin/bash
# Alpine has no RandomizedDelaySec — jitter the run itself so every instance
# in an ASG doesn't hit the AWS API in the same second.
sleep $((RANDOM % 3600))
/opt/app/update-realip.sh
PERIODIC
chmod +x /etc/periodic/daily/ctech-realip

/opt/app/update-realip.sh || echo "realip bootstrap failed — rate limiting will key on HAProxy until the next daily run"
