#!/bin/bash
# Installs /opt/app/deploy.sh, which SSM RunCommand invokes from GitHub Actions
# with the release key as its only argument.
#
# Usage: setup-deploy.sh <deployments-bucket> <binary-name> <health-url>
#   setup-deploy.sh prod-ctech-deployments app http://127.0.0.1:8080/v1.0/health-check
set -euo pipefail

BUCKET="${1:?setup-deploy.sh: deployments bucket required}"
BINARY="${2:?setup-deploy.sh: binary name required}"
HEALTH_URL="${3:?setup-deploy.sh: health check URL required}"

mkdir -p /opt/app/releases

cat > /opt/app/deploy.sh << 'DEPLOY'
#!/bin/bash
# Generated by setup-deploy.sh — do not edit.
# Called by SSM RunCommand with the release key as $1. Expects a zip containing a
# pre-built binary for linux/arm64.
set -euo pipefail

S3_KEY="${1:?deploy.sh: S3 key required}"
RELEASE_DIR="/opt/app/releases/$(date +%Y%m%d_%H%M%S)"
mkdir -p "$RELEASE_DIR"

echo "Downloading release: $S3_KEY"
aws s3 cp "s3://__BUCKET__/$S3_KEY" /tmp/release.zip
unzip -o /tmp/release.zip -d "$RELEASE_DIR"
chmod +x "$RELEASE_DIR/__BINARY__"
chown -R webapp:webapp "$RELEASE_DIR"
ln -sfT "$RELEASE_DIR" /opt/app/current
systemctl restart app 2>/dev/null || systemctl start app

for _ in {1..60}; do
  if curl -sf "__HEALTH_URL__" >/dev/null; then
    echo "Health check passed"
    break
  fi
  if systemctl is-failed --quiet app; then
    echo "Application failed to start"
    journalctl -u app --no-pager -n 100 || true
    exit 1
  fi
  sleep 2
done

curl -sf "__HEALTH_URL__" >/dev/null || {
  echo "Timed out waiting for health check"
  exit 1
}

# Keep only the release that is live; the symlink already points at it.
ls -dt /opt/app/releases/*/ 2>/dev/null | tail -n +2 | xargs rm -rf 2>/dev/null || true
echo "Deployment successful"
DEPLOY

sed -i \
  -e "s|__BUCKET__|${BUCKET}|g" \
  -e "s|__BINARY__|${BINARY}|g" \
  -e "s|__HEALTH_URL__|${HEALTH_URL}|g" \
  /opt/app/deploy.sh

chmod 0755 /opt/app/deploy.sh
