#!/bin/bash
# Installs /opt/app/upload-logs.sh and the logrotate stanza that calls it.
#
# upload-logs.sh runs from logrotate's postrotate hook, so it must never fail the
# rotation: every step exits 0 on trouble.
#
# Usage: setup-logs.sh <logs-bucket> <s3-prefix> <service> <log-dir> [log-dir ...]
#   setup-logs.sh prod-ctech-application-logs ctech-wallet ctech-wallet /var/log/app /var/log/nginx
set -euo pipefail

LOGS_BUCKET="${1:?setup-logs.sh: logs bucket required}"
S3_PREFIX="${2:?setup-logs.sh: S3 prefix required}"
SERVICE="${3:?setup-logs.sh: service name required}"
shift 3
[ "$#" -gt 0 ] || { echo "setup-logs.sh: at least one log directory required" >&2; exit 1; }
LOG_DIRS="$*"

mkdir -p /opt/app

cat > /opt/app/upload-logs.sh << 'UPLOAD'
#!/bin/bash
# Generated by setup-logs.sh — do not edit.
# Bundles what logrotate just rotated and ships it to S3.
# IMDSv2 token required (requireImdsv2 is enforced on this instance).
TOKEN=$(curl -sf -X PUT "http://169.254.169.254/latest/api/token" \
    -H "X-aws-ec2-metadata-token-ttl-seconds: 60")
INSTANCE_ID=$(curl -sf -H "X-aws-ec2-metadata-token: $TOKEN" \
    "http://169.254.169.254/latest/meta-data/instance-id" || echo "unknown")

DATE=$(date +%Y%m%d)
ARCHIVE="/tmp/${DATE}-${INSTANCE_ID}.tar.gz"
ROTATED=$(find __LOG_DIRS__ -name "*-${DATE}.gz" 2>/dev/null)
[ -z "$ROTATED" ] && exit 0

tar czf "$ARCHIVE" $ROTATED 2>/dev/null || exit 0
aws s3 cp "$ARCHIVE" "s3://__LOGS_BUCKET__/__S3_PREFIX__/${DATE}-${INSTANCE_ID}.tar.gz" || exit 0
find __LOG_DIRS__ -name "*-${DATE}.gz" -delete
rm -f "$ARCHIVE"
UPLOAD

sed -i \
  -e "s|__LOG_DIRS__|${LOG_DIRS}|g" \
  -e "s|__LOGS_BUCKET__|${LOGS_BUCKET}|g" \
  -e "s|__S3_PREFIX__|${S3_PREFIX}|g" \
  /opt/app/upload-logs.sh

chmod 0755 /opt/app/upload-logs.sh

# One stanza covering every *.log under the directories we were given. logrotate
# accepts globs, so the list does not have to be enumerated file by file.
{
  for dir in $LOG_DIRS; do
    echo "${dir}/*.log"
  done
  cat << 'LOGROTATE'
{
    daily
    compress
    copytruncate
    missingok
    notifempty
    dateext
    dateformat -%Y%m%d
    rotate 1
    sharedscripts
    postrotate
        /opt/app/upload-logs.sh
    endscript
}
LOGROTATE
} > "/etc/logrotate.d/${SERVICE}"

chmod 0644 "/etc/logrotate.d/${SERVICE}"
