#!/bin/bash
# Installs /opt/app/update-realip.sh plus a systemd oneshot and daily timer, and
# runs it once before nginx first starts.
#
# Without this, nginx's $remote_addr is HAProxy's private IP: every client
# collapses into one rate-limit bucket. Walking X-Forwarded-For right-to-left and
# discarding only trusted hops (HAProxy, then CloudFront's origin-facing ranges)
# is what makes the resolved IP unforgeable — taking the leftmost entry instead
# would let a client spoof the header. CloudFront's ranges change over time and
# have no AAAA record, so they come from the AWS-managed prefix list rather than
# being pinned here, and are refreshed daily.
#
# Requires nginx.conf to `include /etc/nginx/conf.d/realip*.conf;` inside http {}.
#
# Usage: setup-realip.sh <vpc-ipv4-cidr>
set -euo pipefail

VPC_CIDR="${1:?setup-realip.sh: VPC IPv4 CIDR required}"

mkdir -p /opt/app /etc/nginx/conf.d

cat > /opt/app/update-realip.sh << 'REALIP'
#!/bin/bash
set -euo pipefail
CONF=/etc/nginx/conf.d/realip.conf
TMP=$(mktemp)
# systemd units do not inherit /etc/environment, so the dual-stack opt-in must be
# set here for the timer-driven runs.
export AWS_USE_DUALSTACK_ENDPOINT=true
PL_ID=$(aws ec2 describe-managed-prefix-lists \
  --filters Name=prefix-list-name,Values=com.amazonaws.global.cloudfront.origin-facing \
  --query 'PrefixLists[0].PrefixListId' --output text --region us-east-1)
if [ -z "$PL_ID" ] || [ "$PL_ID" = "None" ]; then
  echo "CloudFront origin-facing managed prefix list not found" >&2
  exit 1
fi
PREFIXES=$(aws ec2 get-managed-prefix-list-entries --prefix-list-id "$PL_ID" \
  --query 'Entries[].Cidr' --output text --region us-east-1 | tr '\t' '\n')
# A partial list is worse than the old file: an unlisted edge would be treated as
# the client and become the rate-limit key. Bail and keep what we have.
if [ "$(echo "$PREFIXES" | grep -c .)" -lt 10 ]; then
  echo "Refusing to write realip.conf: only $(echo "$PREFIXES" | grep -c .) CloudFront prefixes returned" >&2
  exit 1
fi
{
  echo "# Generated by /opt/app/update-realip.sh — do not edit."
  echo "set_real_ip_from __VPC_CIDR__;"
  echo "$PREFIXES" | sed -e 's|^|set_real_ip_from |' -e 's|$|;|'
  echo "real_ip_header X-Forwarded-For;"
  echo "real_ip_recursive on;"
} > "$TMP"
install -m 644 "$TMP" "$CONF"
rm -f "$TMP"
# nginx -t reads the live config, so a bad file is caught before it is served.
if ! nginx -t 2>/dev/null; then
  echo "nginx rejected the generated realip.conf — reverting" >&2
  rm -f "$CONF"
  exit 1
fi
# Guarded with `if` rather than `&&`: under `set -e` a false `&&` chain as the
# last statement exits non-zero on the bootstrap run, when nginx is not up yet.
if systemctl is-active --quiet nginx; then
  systemctl reload nginx
fi
REALIP

sed -i "s|__VPC_CIDR__|${VPC_CIDR}|g" /opt/app/update-realip.sh
chmod +x /opt/app/update-realip.sh

cat > /etc/systemd/system/update-realip.service << 'REALIPSVC'
[Unit]
Description=Refresh nginx realip trusted proxy ranges
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/opt/app/update-realip.sh
REALIPSVC

cat > /etc/systemd/system/update-realip.timer << 'REALIPTIMER'
[Unit]
Description=Daily refresh of nginx realip trusted proxy ranges

[Timer]
OnCalendar=daily
RandomizedDelaySec=1h
Persistent=true

[Install]
WantedBy=timers.target
REALIPTIMER

# Generate the file before nginx first starts, so no request is ever served with
# HAProxy as the rate-limit key.
/opt/app/update-realip.sh \
  || echo "realip bootstrap failed — rate limiting will key on HAProxy until the timer succeeds"

systemctl daemon-reload
systemctl enable --now update-realip.timer
