#!/bin/bash
# Generates /opt/app/load-ssm-env.sh from VAR=/ssm/path pairs.
#
# The generated file contains the aws calls, not their results: it is sourced by
# /opt/app/start.sh on every service start, so rotating a secret in SSM takes
# effect on `systemctl restart app` with no redeploy. Nothing secret ever reaches
# the launch template, which is readable by anyone holding
# ec2:DescribeLaunchTemplateVersions.
#
# Every read is best-effort: a parameter that does not exist yet leaves the
# variable empty rather than aborting the boot. Each consumer decides what an
# empty value means — a webhook secret that is empty must refuse to mount its
# route, while an absent cache URL may fall back to an in-memory backend.
#
# Usage: setup-ssm-env.sh VAR=/ssm/path [VAR=/ssm/path ...]
#   setup-ssm-env.sh CTECH_URL=/ctech-account/prod/internal-base-url \
#                    VALKEY_URL=/ctech/prod/valkey/url
set -euo pipefail

OUT=/opt/app/load-ssm-env.sh
mkdir -p /opt/app

[ "$#" -gt 0 ] || { echo "setup-ssm-env.sh: at least one VAR=/ssm/path pair required" >&2; exit 1; }

for pair in "$@"; do
  case "$pair" in
    *=/*) ;;
    *) echo "setup-ssm-env.sh: expected VAR=/ssm/path, got '$pair'" >&2; exit 1 ;;
  esac
done

{
  echo '#!/bin/bash'
  echo '# Generated by setup-ssm-env.sh — do not edit.'
  echo '# Sourced by /opt/app/start.sh on every service start.'
  echo 'AWS_REGION="${AWS_REGION:-us-east-1}"'
  echo '_ctech_ssm(){ aws ssm get-parameter --name "$1" --with-decryption --query Parameter.Value --output text --region "$AWS_REGION" 2>/dev/null || echo ""; }'
  for pair in "$@"; do
    name="${pair%%=*}"
    ssm_path="${pair#*=}"
    printf '%s=$(_ctech_ssm %q)\n' "$name" "$ssm_path"
    printf 'export %s\n' "$name"
  done
} > "$OUT"

chmod 0755 "$OUT"
chown webapp:webapp "$OUT"
