#!/bin/bash
# Installs /opt/app/deploy.sh, which SSM RunCommand invokes from GitHub Actions
# with the release key as its only argument.
#
# Usage: setup-deploy.sh <deployments-bucket> <binary-name> <health-url> [extra binaries...]
#   setup-deploy.sh prod-ctech-deployments app http://127.0.0.1:8080/v1.0/health-check
#   setup-deploy.sh prod-ctech-deployments app http://…/health sweep reconcile
#
# The extra binaries are the one-shot job binaries a release ships alongside the
# service: they need the exec bit too, and a zip does not carry it reliably.
#
# No argument here selects zero-downtime rolling deploy — it is auto-detected
# at deploy time from /opt/app/alt-port (setup-app-service.sh's alt-port
# argument) and /opt/app/app-port (setup-nginx.sh's app-port-alt argument).
# Instances without those files get the traditional single restart; instances
# with them roll app then app2, health-gating each directly on its own port.
set -euo pipefail

BUCKET="${1:?setup-deploy.sh: deployments bucket required}"
BINARY="${2:?setup-deploy.sh: binary name required}"
HEALTH_URL="${3:?setup-deploy.sh: health check URL required}"
shift 3
BINARIES="$BINARY $*"

mkdir -p /opt/app/releases

cat > /opt/app/deploy.sh << 'DEPLOY'
#!/bin/bash
# Generated by setup-deploy.sh — do not edit.
# Called by SSM RunCommand with the release key as $1. Expects a zip containing a
# pre-built binary for linux/arm64.
set -euo pipefail

S3_KEY="${1:?deploy.sh: S3 key required}"
RELEASE_DIR="/opt/app/releases/$(date +%Y%m%d_%H%M%S)"
mkdir -p "$RELEASE_DIR"

echo "Downloading release: $S3_KEY"
aws s3 cp "s3://__BUCKET__/$S3_KEY" /tmp/release.zip
unzip -o /tmp/release.zip -d "$RELEASE_DIR"
for b in __BINARIES__; do chmod +x "$RELEASE_DIR/$b"; done
chown -R webapp:webapp "$RELEASE_DIR"
ln -sfT "$RELEASE_DIR" /opt/app/current

restart_and_wait() {
  local unit="$1" url="$2"
  systemctl restart "$unit" 2>/dev/null || systemctl start "$unit"
  for _ in {1..60}; do
    if curl -sf "$url" >/dev/null; then
      echo "$unit: health check passed"
      return 0
    fi
    if systemctl is-failed --quiet "$unit"; then
      echo "$unit: application failed to start"
      journalctl -u "$unit" --no-pager -n 100 || true
      exit 1
    fi
    sleep 2
  done
  curl -sf "$url" >/dev/null || { echo "$unit: timed out waiting for health check"; exit 1; }
}

if [ -f /opt/app/alt-port ]; then
  # Rolling: app then app2, one at a time. Gate each directly on its own
  # port, never through nginx — nginx round-robins, so it would keep
  # answering from whichever unit is still up and mask the one that just
  # restarted. __HEALTH_URL__ may point at nginx (the company convention);
  # only its path is reused here, not its host:port.
  APP_PORT="$(cat /opt/app/app-port)"
  ALT_PORT="$(cat /opt/app/alt-port)"
  HEALTH_PATH="$(echo "__HEALTH_URL__" | sed -E 's#^[a-z]+://[^/]+##')"
  restart_and_wait app "http://127.0.0.1:${APP_PORT}${HEALTH_PATH}"
  restart_and_wait app2 "http://127.0.0.1:${ALT_PORT}${HEALTH_PATH}"
else
  restart_and_wait app "__HEALTH_URL__"
fi

# Keep only the release that is live; the symlink already points at it.
ls -dt /opt/app/releases/*/ 2>/dev/null | tail -n +2 | xargs rm -rf 2>/dev/null || true
echo "Deployment successful"
DEPLOY

sed -i \
  -e "s|__BUCKET__|${BUCKET}|g" \
  -e "s|__BINARIES__|${BINARIES}|g" \
  -e "s|__HEALTH_URL__|${HEALTH_URL}|g" \
  /opt/app/deploy.sh

chmod 0755 /opt/app/deploy.sh
